use std::{
    sync::Arc,
    time::{Duration, Instant},
};

use axum::{
    Json,
    extract::{Multipart, State},
    http::StatusCode,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;
use uuid::Uuid;

use crate::{AppState, config::Config, error::ApiError};

pub const MAX_ASSET_BYTES: usize = 10 * 1024 * 1024;
#[derive(Serialize, sqlx::FromRow)]
pub struct Asset {
    pub id: Uuid,
    pub filename: String,
    pub url: String,
    pub content_type: String,
    pub size: i64,
    pub created_at: DateTime<Utc>,
}
#[derive(Clone)]
pub struct Storage {
    config: Arc<Config>,
    client: reqwest::Client,
    token: Arc<Mutex<Option<CachedToken>>>,
}
struct CachedToken {
    value: String,
    expires: Instant,
}
#[derive(Deserialize)]
struct MetadataToken {
    access_token: String,
    expires_in: u64,
}

impl Storage {
    pub fn new(config: Arc<Config>, client: reqwest::Client) -> Self {
        Self {
            config,
            client,
            token: Arc::new(Mutex::new(None)),
        }
    }
    async fn access_token(&self) -> Result<String, ApiError> {
        let mut cached = self.token.lock().await;
        if let Some(token) = &*cached
            && token.expires > Instant::now()
        {
            return Ok(token.value.clone());
        }
        let token = self.client.get("http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token")
            .header("Metadata-Flavor", "Google").send().await.and_then(reqwest::Response::error_for_status).map_err(ApiError::internal)?
            .json::<MetadataToken>().await.map_err(ApiError::internal)?;
        let expires = Instant::now() + Duration::from_secs(token.expires_in.saturating_sub(60));
        let value = token.access_token;
        *cached = Some(CachedToken {
            value: value.clone(),
            expires,
        });
        Ok(value)
    }
    async fn write(&self, key: &str, bytes: Vec<u8>, content_type: &str) -> Result<(), ApiError> {
        if self.config.storage_backend == "local" {
            tokio::fs::create_dir_all(&self.config.local_asset_path)
                .await
                .map_err(ApiError::internal)?;
            // UUID paths are generated by the API; uploaded filenames are never filesystem paths.
            tokio::fs::write(self.config.local_asset_path.join(key), bytes)
                .await
                .map_err(ApiError::internal)?;
            return Ok(());
        }
        let bucket = self
            .config
            .gcs_bucket
            .as_ref()
            .ok_or_else(|| ApiError::internal("GCS bucket missing"))?;
        let boundary = Uuid::new_v4().to_string();
        let metadata = serde_json::json!({ "name": key, "contentType": content_type, "cacheControl": "public,max-age=31536000,immutable", "contentDisposition": if content_type == "application/pdf" { "attachment" } else { "inline" } });
        let mut payload = format!("--{boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n{metadata}\r\n--{boundary}\r\nContent-Type: {content_type}\r\n\r\n").into_bytes();
        payload.extend_from_slice(&bytes);
        payload.extend_from_slice(format!("\r\n--{boundary}--\r\n").as_bytes());
        self.client
            .post(format!(
                "https://storage.googleapis.com/upload/storage/v1/b/{bucket}/o"
            ))
            .query(&[("uploadType", "multipart"), ("ifGenerationMatch", "0")])
            .bearer_auth(self.access_token().await?)
            .header(
                "Content-Type",
                format!("multipart/related; boundary={boundary}"),
            )
            .body(payload)
            .send()
            .await
            .and_then(reqwest::Response::error_for_status)
            .map_err(ApiError::internal)?;
        Ok(())
    }
    async fn remove(&self, key: &str) -> Result<(), ApiError> {
        if self.config.storage_backend == "local" {
            tokio::fs::remove_file(self.config.local_asset_path.join(key))
                .await
                .map_err(ApiError::internal)?;
        } else {
            let bucket = self
                .config
                .gcs_bucket
                .as_ref()
                .ok_or_else(|| ApiError::internal("GCS bucket missing"))?;
            self.client
                .delete(format!(
                    "https://storage.googleapis.com/storage/v1/b/{bucket}/o/{key}"
                ))
                .bearer_auth(self.access_token().await?)
                .send()
                .await
                .and_then(reqwest::Response::error_for_status)
                .map_err(ApiError::internal)?;
        }
        Ok(())
    }
}
fn media_type(bytes: &[u8]) -> Option<(&'static str, &'static str)> {
    if bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
        Some(("image/png", "png"))
    } else if bytes.starts_with(b"\xff\xd8\xff") {
        Some(("image/jpeg", "jpg"))
    } else if bytes.starts_with(b"GIF87a") || bytes.starts_with(b"GIF89a") {
        Some(("image/gif", "gif"))
    } else if bytes.len() >= 12 && bytes.starts_with(b"RIFF") && &bytes[8..12] == b"WEBP" {
        Some(("image/webp", "webp"))
    } else if bytes.starts_with(b"%PDF-") {
        Some(("application/pdf", "pdf"))
    } else {
        None
    }
}
fn safe_filename(filename: &str) -> String {
    let filename = filename.rsplit(['/', '\\']).next().unwrap_or("asset");
    let sanitized: String = filename
        .chars()
        .filter(|c| !c.is_control())
        .take(200)
        .collect();
    if sanitized.trim().is_empty() {
        "asset".into()
    } else {
        sanitized
    }
}
pub async fn list(State(state): State<AppState>) -> Result<Json<Vec<Asset>>, ApiError> {
    Ok(Json(sqlx::query_as::<_, Asset>("SELECT id,filename,url,content_type,size,created_at FROM assets ORDER BY created_at DESC").fetch_all(&state.pool).await?))
}
pub async fn upload(
    State(state): State<AppState>,
    mut multipart: Multipart,
) -> Result<(StatusCode, Json<Asset>), ApiError> {
    let mut file = multipart
        .next_field()
        .await
        .map_err(|_| ApiError::bad_request("Invalid multipart upload"))?
        .ok_or_else(|| ApiError::bad_request("A file field is required"))?;
    if file.name() != Some("file") {
        return Err(ApiError::bad_request("Multipart field must be named file"));
    }
    let filename = safe_filename(file.file_name().unwrap_or("asset"));
    let mut bytes = Vec::new();
    while let Some(chunk) = file
        .chunk()
        .await
        .map_err(|_| ApiError(StatusCode::PAYLOAD_TOO_LARGE, "Invalid or oversized upload"))?
    {
        if bytes.len() + chunk.len() > MAX_ASSET_BYTES {
            return Err(ApiError(
                StatusCode::PAYLOAD_TOO_LARGE,
                "File must be at most 10 MiB",
            ));
        }
        bytes.extend_from_slice(&chunk);
    }
    drop(file);
    if multipart
        .next_field()
        .await
        .map_err(|_| ApiError::bad_request("Invalid multipart upload"))?
        .is_some()
    {
        return Err(ApiError::bad_request("Upload exactly one file at a time"));
    }
    let (content_type, extension) = media_type(&bytes).ok_or_else(|| {
        ApiError::bad_request("Only PNG, JPEG, WebP, GIF and PDF files are supported")
    })?;
    let id = Uuid::new_v4();
    let key = format!("{id}.{extension}");
    let size = bytes.len() as i64;
    let url = format!("{}/{key}", state.config.assets_base_url);
    state.storage.write(&key, bytes, content_type).await?;
    let result = sqlx::query_as::<_, Asset>("INSERT INTO assets (id,filename,storage_key,url,content_type,size) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,filename,url,content_type,size,created_at")
        .bind(id).bind(filename).bind(&key).bind(url).bind(content_type).bind(size).fetch_one(&state.pool).await;
    match result {
        Ok(asset) => Ok((StatusCode::CREATED, Json(asset))),
        Err(error) => {
            if state.storage.remove(&key).await.is_err() {
                tracing::error!(storage_key = %key, "Failed to remove orphaned upload after database failure");
            }
            Err(error.into())
        }
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn recognizes_only_supported_signatures() {
        assert_eq!(
            media_type(b"\x89PNG\r\n\x1a\nrest"),
            Some(("image/png", "png"))
        );
        assert_eq!(media_type(b"%PDF-1.7"), Some(("application/pdf", "pdf")));
        for bytes in [b"<svg><script>".as_slice(), b"<html>", b"", b"RIFFbad!"] {
            assert_eq!(media_type(bytes), None);
        }
    }
    #[test]
    fn client_filenames_are_metadata_only() {
        assert_eq!(safe_filename("../../etc/passwd"), "passwd");
        assert_eq!(safe_filename("C:\\secret\\photo.png"), "photo.png");
        assert_eq!(safe_filename("bad\r\nname.png"), "badname.png");
    }
}
